"""add_recycling_module

Revision ID: 7bde6e1a4cdb
Revises: 0019_add_company_bank_details
Create Date: 2026-07-10 15:54:26.881459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bde6e1a4cdb'
down_revision: Union[str, None] = '0019_add_company_bank_details'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('finished_product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('expected_loss_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_finished_product_id'), 'recipes', ['finished_product_id'], unique=True)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_is_active'), 'recipes', ['is_active'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_table('direct_sales',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('purchase_cost', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_sales_branch_id'), 'direct_sales', ['branch_id'], unique=False)
    op.create_index(op.f('ix_direct_sales_customer_id'), 'direct_sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_direct_sales_id'), 'direct_sales', ['id'], unique=False)
    op.create_index(op.f('ix_direct_sales_is_active'), 'direct_sales', ['is_active'], unique=False)
    op.create_index(op.f('ix_direct_sales_product_id'), 'direct_sales', ['product_id'], unique=False)
    op.create_table('production_entries',
    sa.Column('finished_product_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('input_weight', sa.Float(), nullable=False),
    sa.Column('output_weight', sa.Float(), nullable=False),
    sa.Column('weight_loss', sa.Float(), nullable=False),
    sa.Column('loss_percentage', sa.Float(), nullable=False),
    sa.Column('production_expenses', sa.Float(), nullable=False),
    sa.Column('raw_material_cost', sa.Float(), nullable=False),
    sa.Column('component_cost', sa.Float(), nullable=False),
    sa.Column('total_production_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finished_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_entries_branch_id'), 'production_entries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_production_entries_finished_product_id'), 'production_entries', ['finished_product_id'], unique=False)
    op.create_index(op.f('ix_production_entries_id'), 'production_entries', ['id'], unique=False)
    op.create_index(op.f('ix_production_entries_is_active'), 'production_entries', ['is_active'], unique=False)
    op.create_table('recipe_items',
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_items_id'), 'recipe_items', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_items_is_active'), 'recipe_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_recipe_items_product_id'), 'recipe_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_recipe_id'), 'recipe_items', ['recipe_id'], unique=False)
    op.create_table('production_consumed_items',
    sa.Column('production_entry_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_entry_id'], ['production_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_consumed_items_id'), 'production_consumed_items', ['id'], unique=False)
    op.create_index(op.f('ix_production_consumed_items_is_active'), 'production_consumed_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_production_consumed_items_product_id'), 'production_consumed_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_production_consumed_items_production_entry_id'), 'production_consumed_items', ['production_entry_id'], unique=False)
    op.create_table('raw_material_receipts',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_receipts_branch_id'), 'raw_material_receipts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_raw_material_receipts_id'), 'raw_material_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_raw_material_receipts_is_active'), 'raw_material_receipts', ['is_active'], unique=False)
    op.create_index(op.f('ix_raw_material_receipts_product_id'), 'raw_material_receipts', ['product_id'], unique=False)
    op.create_index(op.f('ix_raw_material_receipts_supplier_id'), 'raw_material_receipts', ['supplier_id'], unique=False)
    op.drop_index('ix_deliveries_id', table_name='deliveries')
    op.drop_index('ix_deliveries_is_active', table_name='deliveries')
    op.drop_index('ix_deliveries_sales_order_id', table_name='deliveries')
    op.drop_table('deliveries')
    op.create_index(op.f('ix_account_groups_id'), 'account_groups', ['id'], unique=False)
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_is_active'), 'journal_entries', ['is_active'], unique=False)
    op.create_index(op.f('ix_journal_entries_voucher_type_id'), 'journal_entries', ['voucher_type_id'], unique=False)
    op.drop_index('ix_journal_lines_ledger_id', table_name='journal_entry_lines')
    op.create_index(op.f('ix_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_ledger_id'), 'journal_entry_lines', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_ledger_accounts_id'), 'ledger_accounts', ['id'], unique=False)
    op.add_column('products', sa.Column('product_type', sa.String(length=20), nullable=False))
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_purchase_entries_journal_entry_id'), 'purchase_entries', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_payable_ledger_id'), 'purchase_entries', ['payable_ledger_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_purchase_account_id'), 'purchase_entries', ['purchase_account_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_tax_ledger_id'), 'purchase_entries', ['tax_ledger_id'], unique=False)
    op.add_column('purchase_returns', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('purchase_returns', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('purchase_returns', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint('purchase_returns_return_number_key', 'purchase_returns', type_='unique')
    op.create_index(op.f('ix_purchase_returns_branch_id'), 'purchase_returns', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_debit_note_ledger_id'), 'purchase_returns', ['debit_note_ledger_id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_id'), 'purchase_returns', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_is_active'), 'purchase_returns', ['is_active'], unique=False)
    op.create_index(op.f('ix_purchase_returns_journal_entry_id'), 'purchase_returns', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_purchase_entry_id'), 'purchase_returns', ['purchase_entry_id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_return_number'), 'purchase_returns', ['return_number'], unique=True)
    op.create_index(op.f('ix_purchase_returns_supplier_id'), 'purchase_returns', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_product_id'), 'stock_transfer_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_transfer_id'), 'stock_transfer_items', ['transfer_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_destination_branch_id'), 'stock_transfers', ['destination_branch_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_source_branch_id'), 'stock_transfers', ['source_branch_id'], unique=False)
    op.create_index(op.f('ix_suppliers_default_payable_ledger_id'), 'suppliers', ['default_payable_ledger_id'], unique=False)
    op.create_index(op.f('ix_vendor_payments_id'), 'vendor_payments', ['id'], unique=False)
    op.create_index(op.f('ix_voucher_types_id'), 'voucher_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_types_id'), table_name='voucher_types')
    op.drop_index(op.f('ix_vendor_payments_id'), table_name='vendor_payments')
    op.drop_index(op.f('ix_suppliers_default_payable_ledger_id'), table_name='suppliers')
    op.drop_index(op.f('ix_stock_transfers_source_branch_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_destination_branch_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfer_items_transfer_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_product_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_purchase_returns_supplier_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_return_number'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_purchase_entry_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_journal_entry_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_is_active'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_debit_note_ledger_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_branch_id'), table_name='purchase_returns')
    op.create_unique_constraint('purchase_returns_return_number_key', 'purchase_returns', ['return_number'])
    op.drop_column('purchase_returns', 'is_active')
    op.drop_column('purchase_returns', 'updated_at')
    op.drop_column('purchase_returns', 'created_at')
    op.drop_index(op.f('ix_purchase_entries_tax_ledger_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_purchase_account_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_payable_ledger_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_journal_entry_id'), table_name='purchase_entries')
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('products', 'product_type')
    op.drop_index(op.f('ix_ledger_accounts_id'), table_name='ledger_accounts')
    op.drop_index(op.f('ix_journal_entry_lines_ledger_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_id'), table_name='journal_entry_lines')
    op.create_index('ix_journal_lines_ledger_id', 'journal_entry_lines', ['ledger_id'], unique=False)
    op.drop_index(op.f('ix_journal_entries_voucher_type_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_is_active'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_index(op.f('ix_account_groups_id'), table_name='account_groups')
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sales_order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('delivery_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('qty_delivered', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name='deliveries_sales_order_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='deliveries_pkey')
    )
    op.create_index('ix_deliveries_sales_order_id', 'deliveries', ['sales_order_id'], unique=False)
    op.create_index('ix_deliveries_is_active', 'deliveries', ['is_active'], unique=False)
    op.create_index('ix_deliveries_id', 'deliveries', ['id'], unique=False)
    op.drop_index(op.f('ix_raw_material_receipts_supplier_id'), table_name='raw_material_receipts')
    op.drop_index(op.f('ix_raw_material_receipts_product_id'), table_name='raw_material_receipts')
    op.drop_index(op.f('ix_raw_material_receipts_is_active'), table_name='raw_material_receipts')
    op.drop_index(op.f('ix_raw_material_receipts_id'), table_name='raw_material_receipts')
    op.drop_index(op.f('ix_raw_material_receipts_branch_id'), table_name='raw_material_receipts')
    op.drop_table('raw_material_receipts')
    op.drop_index(op.f('ix_production_consumed_items_production_entry_id'), table_name='production_consumed_items')
    op.drop_index(op.f('ix_production_consumed_items_product_id'), table_name='production_consumed_items')
    op.drop_index(op.f('ix_production_consumed_items_is_active'), table_name='production_consumed_items')
    op.drop_index(op.f('ix_production_consumed_items_id'), table_name='production_consumed_items')
    op.drop_table('production_consumed_items')
    op.drop_index(op.f('ix_recipe_items_recipe_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_product_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_is_active'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_id'), table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_production_entries_is_active'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_id'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_finished_product_id'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_branch_id'), table_name='production_entries')
    op.drop_table('production_entries')
    op.drop_index(op.f('ix_direct_sales_product_id'), table_name='direct_sales')
    op.drop_index(op.f('ix_direct_sales_is_active'), table_name='direct_sales')
    op.drop_index(op.f('ix_direct_sales_id'), table_name='direct_sales')
    op.drop_index(op.f('ix_direct_sales_customer_id'), table_name='direct_sales')
    op.drop_index(op.f('ix_direct_sales_branch_id'), table_name='direct_sales')
    op.drop_table('direct_sales')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_is_active'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_finished_product_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
