"""isolate_current_stock

Revision ID: 9a9ef6b1fddd
Revises: 53a1035d7771
Create Date: 2026-07-15 16:07:24.306552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9ef6b1fddd'
down_revision: Union[str, None] = '53a1035d7771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE current_stock CASCADE")
    op.add_column('current_stock', sa.Column('company_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_current_stock_product_id', table_name='current_stock')
    op.create_index(op.f('ix_current_stock_product_id'), 'current_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_current_stock_company_id'), 'current_stock', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'current_stock', ['product_id', 'company_id'])
    op.create_foreign_key(None, 'current_stock', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'current_stock', type_='foreignkey')
    op.drop_constraint(None, 'current_stock', type_='unique')
    op.drop_index(op.f('ix_current_stock_company_id'), table_name='current_stock')
    op.drop_index(op.f('ix_current_stock_product_id'), table_name='current_stock')
    op.create_index('ix_current_stock_product_id', 'current_stock', ['product_id'], unique=False)
    op.drop_column('current_stock', 'company_id')
    # ### end Alembic commands ###
