"""add_manufacturing

Revision ID: ad0df63dce68
Revises: 7bde6e1a4cdb
Create Date: 2026-07-14 13:58:51.649304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0df63dce68'
down_revision: Union[str, None] = '7bde6e1a4cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturing_processes',
    sa.Column('manufacturing_no', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_to_recycle_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('process_expenses', sa.Float(), nullable=False),
    sa.Column('output_product_id', sa.Uuid(), nullable=True),
    sa.Column('output_weight', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['output_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_to_recycle_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturing_processes_branch_id'), 'manufacturing_processes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_manufacturing_processes_id'), 'manufacturing_processes', ['id'], unique=False)
    op.create_index(op.f('ix_manufacturing_processes_is_active'), 'manufacturing_processes', ['is_active'], unique=False)
    op.create_index(op.f('ix_manufacturing_processes_manufacturing_no'), 'manufacturing_processes', ['manufacturing_no'], unique=True)
    op.create_index(op.f('ix_manufacturing_processes_product_to_recycle_id'), 'manufacturing_processes', ['product_to_recycle_id'], unique=False)
    op.create_table('manufacturing_process_items',
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('bom_qty', sa.Float(), nullable=False),
    sa.Column('actual_qty_used', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['manufacturing_processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturing_process_items_id'), 'manufacturing_process_items', ['id'], unique=False)
    op.create_index(op.f('ix_manufacturing_process_items_is_active'), 'manufacturing_process_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_manufacturing_process_items_process_id'), 'manufacturing_process_items', ['process_id'], unique=False)
    op.create_index(op.f('ix_manufacturing_process_items_product_id'), 'manufacturing_process_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manufacturing_process_items_product_id'), table_name='manufacturing_process_items')
    op.drop_index(op.f('ix_manufacturing_process_items_process_id'), table_name='manufacturing_process_items')
    op.drop_index(op.f('ix_manufacturing_process_items_is_active'), table_name='manufacturing_process_items')
    op.drop_index(op.f('ix_manufacturing_process_items_id'), table_name='manufacturing_process_items')
    op.drop_table('manufacturing_process_items')
    op.drop_index(op.f('ix_manufacturing_processes_product_to_recycle_id'), table_name='manufacturing_processes')
    op.drop_index(op.f('ix_manufacturing_processes_manufacturing_no'), table_name='manufacturing_processes')
    op.drop_index(op.f('ix_manufacturing_processes_is_active'), table_name='manufacturing_processes')
    op.drop_index(op.f('ix_manufacturing_processes_id'), table_name='manufacturing_processes')
    op.drop_index(op.f('ix_manufacturing_processes_branch_id'), table_name='manufacturing_processes')
    op.drop_table('manufacturing_processes')
    # ### end Alembic commands ###
